#server:
    #port: 8080
    #context-path: #/lovepei/

#logging:
    #level:
        #com.loepei.sandwich: TRACE

spring:
    datasource:
        name: dev
        url: jdbc:mysql://localhost:3306/qandp?useUnicode=true&characterEncoding=utf-8
        username: root
        password: fuq
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mvc:
        view:
            prefix: /templates/
            suffix: .ftl



mybatis:
    type-aliases-package: com.lovepei.sandwich.domain
    mapper-locations: classpath:mapper/*.xml

#pagehelper:
    #helperDialect: mysql
    #reasonable: true
    #supportMethodsArguments: true
    #params: count=countSql